CREATE OR REPLACE VIEW POLIBRAS.VWP_VENDEDOR
(u_pkey, u_orgvenda, s_codigo, s_nome, d_vendmes, u_metacli, u_metaprod, t_datainic, t_datafinal, d_comissao, d_sd_cc, d_maxdeb, d_maxdesc, u_status, s_cnpj_cpf)
AS
SELECT 
	 0 AS U_PKEY,
	 CAST(A.NROEMPRESA AS NUMBER) AS U_ORGVENDA,
	 CAST(A.NROREPRESENTANTE AS VARCHAR2(1000)) AS S_CODIGO,
	 CAST(A.APELIDO AS VARCHAR2(1000)) AS S_NOME,
	 replace(CAST(0 AS NUMBER(18, 6)),',','.') AS D_META_VENDA_MENSAL,
	 0 AS U_META_CLIENTE,
	 0 AS U_META_PRODUTO,
	 TO_DATE('1900-01-01 01:00:00', 'yyyy-mm-dd hh24:mi:ss') AS T_DATA_INICIAL,
	 TO_DATE('1900-01-10 01:00:00', 'yyyy-mm-dd hh24:mi:ss') AS T_DATA_FINAL,
	 replace(CAST(nvl(a.percmaxacrflex,0) AS NUMBER(18, 6)),',','.') AS D_COMISSAO,
	 replace(CAST(nvl(D.VLRSALDOPEDFLEX,0) AS NUMBER(18, 6)),',','.') AS D_SD_CC,
	 replace(CAST(0 AS NUMBER(18, 6)) ,',','.')AS D_MAX_DEB,
	 replace(CAST(nvl(a.percmaxdescflex,0) AS NUMBER(18, 6)) ,',','.') AS D_MAX_DESC,
	 A.NROEMPRESA AS U_STATUS,
	 CAST(IMPLANTACAO.FC5MASKCNPJCPF(B.NROCGCCPF, B.DIGCGCCPF, B.FISICAJURIDICA) AS VARCHAR(1000)) AS S_CNPJ_CPF
FROM IMPLANTACAO.MAD_REPRESENTANTE A
JOIN IMPLANTACAO.GE_PESSOA B ON (b.SEQPESSOA = a.SEQPESSOA)
LEFT JOIN IMPLANTACAO.MAD_REPSALDO D ON ( d.NROREPRESENTANTE = a.NROREPRESENTANTE)
WHERE
A.STATUS = 'A'
--AND a.nrorepresentante = 57
ORDER BY A.NROREPRESENTANTE

