CREATE OR REPLACE VIEW POLIBRAS.VWP_TABELA_PRECO AS
select
t.U_PKEY, t.U_ORGVENDA, t.S_CODTABELA, t.S_CODPRODUTO, t.D_FAIXA, t.U_REFERENCIA, t.D_PRECO, t.D_DESCONTOPADRAO,
t.D_CVERBADESC, t.D_CVERBAACRES, t.U_SITUACAO
from (
SELECT * FROM polibras.cadan_tab_preco
) T

