CREATE OR REPLACE VIEW POLIBRAS.VWP_VENDEDOR 
(U_PKEY, U_ORGVENDA, S_CODIGO, S_NOME, D_VENDMES, U_METACLI, U_METAPROD, T_DATAINIC, T_DATAFINAL, D_COMISSAO, D_SD_CC, D_MAXDEB, D_MAXDESC, U_STATUS, S_CNPJ_CPF)
AS
SELECT			
    DISTINCT
    0 AS U_PKEY,
    CAST(A.NROEMPRESA AS NUMBER) AS U_ORGVENDA,
    CAST(A.NROREPRESENTANTE AS VARCHAR2(1000)) AS S_CODIGO,
    CAST(A.APELIDO AS VARCHAR2(1000)) AS S_NOME,
    REPLACE(CAST(0 AS NUMBER(18, 6)),',','.') AS D_META_VENDA_MENSAL,
    0 AS U_META_CLIENTE,
    0 AS U_META_PRODUTO,
    TO_DATE('1900-01-01 01:00:00', 'YYYY-MM-DD HH24:MI:SS') AS T_DATA_INICIAL,
    TO_DATE('1900-01-10 01:00:00', 'YYYY-MM-DD HH24:MI:SS') AS T_DATA_FINAL,
    REPLACE(CAST(NVL(A.PERCMAXACRFLEX,0) AS NUMBER(18, 6)),',','.') AS D_COMISSAO,
		-- Comentado em 23/08/2024 por Hilson Santos			 
		/*REPLACE(CAST(NVL(D.VLRSALDOPEDFLEX,0) AS NUMBER(18, 6)),',','.') AS D_SD_CC,*/
		-- Incluido em 23/08/2024 por Hilson Santos
    REPLACE(CAST(NVL(SUM(C.VALOR),0) AS NUMBER(18, 6)),',','.') AS D_SD_CC,
    REPLACE(CAST(0 AS NUMBER(18, 6)) ,',','.')AS D_MAX_DEB,
    REPLACE(CAST(NVL(A.PERCMAXDESCFLEX,0) AS NUMBER(18, 6)) ,',','.') AS D_MAX_DESC,
    A.NROEMPRESA AS U_STATUS,
    CAST(IMPLANTACAO.FC5MASKCNPJCPF(B.NROCGCCPF,B.DIGCGCCPF,B.FISICAJURIDICA) AS VARCHAR(1000)) AS S_CNPJ_CPF
FROM IMPLANTACAO.MAD_REPRESENTANTE A
JOIN IMPLANTACAO.GE_PESSOA B ON (B.SEQPESSOA = A.SEQPESSOA)	 
-- Comentado em 23/08/2024 por Hilson Santos
/*LEFT JOIN IMPLANTACAO.MAD_REPSALDO C ON C.NROREPRESENTANTE = A.NROREPRESENTANTE*/
-- Incluido em 23/08/2024 por Hilson Santos
LEFT JOIN IMPLANTACAO.MAD_REPCCFLEX C ON C.NROREPRESENTANTE = A.NROREPRESENTANTE AND C.SITUACAOLANCTO = 'A' AND C.DTALANCAMENTO >= TRUNC(ADD_MONTHS(SYSDATE, 0),'MM')
LEFT JOIN IMPLANTACAO.MAD_PEDVENDA D ON D.NROPEDVENDA = C.NROPEDVENDA AND D.NROREPRESENTANTE = C.NROREPRESENTANTE
WHERE A.STATUS = 'A'
AND (D.SITUACAOPED IS NULL OR(D.SITUACAOPED = 'F' AND C.VALOR > 0) OR (D.SITUACAOPED != 'F' AND C.VALOR < 0))
--AND A.NROREPRESENTANTE = 300
-- Incluido em 23/08/2024 por Hilson Santos	
GROUP BY A.NROEMPRESA, A.NROREPRESENTANTE, A.APELIDO, A.PERCMAXACRFLEX, A.PERCMAXDESCFLEX, B.NROCGCCPF, B.DIGCGCCPF, B.FISICAJURIDICA
ORDER BY 3 ASC																																														  
