SELECT 
    a.nroempresa                    AS  codigo,
    'N'                             AS  aceitavendasemest,
    'N'                             AS  alterarcobbkchautomatico,
    'N'                             AS  autoservico,
    a.bairro                        AS  bairro,
    'N'                             AS  bloquearpedidosabaixovlminimo,
    'N'                             AS  calcularipivenda,
    a.cep                           AS  cep,
    SUBSTR(a.nrocgc||a.digcgc,1,14) AS  cgc,
    a.cidade                        AS  cidade,
    a.seqpessoa                     AS  codcli,
    'N'                             AS  considerarcomissaozero,
    a.endereco                      AS  endereco,
    SUBSTR(a.faxddd||a.faxnro,1,14) AS  fax,
    SUBSTR(a.inscrestadual, 1, 20)  AS  ie,
    'N'                             AS  lancarfretepesoautfat,
    a.razaosocial                   AS  razaosocial,
    SUBSTR(a.ddd||a.fonenro,1,18)   AS  telefone,
    0                               AS  tipoavaliacaocomissao,
    NULL                            AS  tipofretauto,
    'A'                             AS  tipoprecificacao,
    a.estado                        AS  uf,
    'N'                             AS  usaestoquedepfechado,
    'N'                             AS  usawms,
    'S'                             AS  utilizanfe,
    NULL                            AS  broker,
    NULL                            AS  tipobroker,
    'S'                             AS  utilizavendaporembalagem,
    a.status,
    TO_DATE(a.dtaalteracao)         AS  dtaalteracao
FROM implantacao.ge_empresa a 
WHERE 1 = 1
ORDER BY 1 ASC;