CREATE TABLE IMPLANTACAO.CADAN_PRODUTOBASE
(
  SEQPRODUTO   VARCHAR2(10) NOT NULL,
  JSONDATA     VARCHAR2(255) NOT NULL,
  DTAINCLUSAO  DATE NOT NULL,
  DTAALTERACAO DATE NOT NULL,
  STATUS       VARCHAR2(1) DEFAULT 'A' NOT NULL,
	CONSTRAINT CADAN_PRODUTOBASE PRIMARY KEY (SEQPRODUTO)
)