SELECT 	
    PVENDA.NROPEDVENDA,
		PVENDA.DTABASEFATURAMENTO,
	  SUM((FAMEMB.PESOBRUTO / PVENDAITEM.QTDEMBALAGEM) * PVENDAITEM.QTDATENDIDA),
    SUM(PVENDAITEM.VLREMBINFORMADO * (PVENDAITEM.QTDATENDIDA / PVENDAITEM.QTDEMBALAGEM))
FROM 	
    implantacao.MADV_PEDVENDAROTEIRIZACAO PVENDA,
		implantacao.MAD_ROTA ROTA,
		implantacao.MAD_PRACA PRACA,
    implantacao.MAD_CLIENTEEND CLIENTE,
		implantacao.MAD_PEDVENDAITEM PVENDAITEM,
    implantacao.MAP_PRODUTO PROD,
		implantacao.MAP_FAMEMBALAGEM FAMEMB,
		implantacao.GE_PESSOA PESSOA 
WHERE 1=1
AND		PVENDA.NROPEDVENDA = PVENDAITEM.NROPEDVENDA
AND		PVENDA.NROEMPRESA = PVENDAITEM.NROEMPRESA
AND		PVENDA.SEQPESSOA = CLIENTE.SEQPESSOA
AND		NVL(PVENDA.SEQPESSOAEND,0) = CLIENTE.SEQPESSOAEND
AND		PVENDA.SEQPESSOA = PESSOA.SEQPESSOA
AND		CLIENTE.SEQPRACA = PRACA.SEQPRACA
AND		PRACA.SEQROTA = ROTA.SEQROTA
AND		PVENDAITEM.SEQPRODUTO	= PROD.SEQPRODUTO
AND		PROD.SEQFAMILIA = FAMEMB.SEQFAMILIA
AND		PVENDAITEM.QTDEMBALAGEM = FAMEMB.QTDEMBALAGEM
AND 	PVENDA.NROEMPRESA IN (1) 
AND 	ROTA.SEQSETOR IN (2, 21, 35, 20, 22) 
AND 	(pvenda.geralteracaoestq = 'S' OR pvenda.geralteracaoestq IS NULL)
AND		PVENDA.DTABASEFATURAMENTO BETWEEN SYSDATE-9 AND SYSDATE            
AND		PVENDA.INDPERMFATANTECIPADO	=	'S'
AND 	INDENTREGARETIRA = 'E'                               
AND		PVENDA.DTAROTEIRIZACAO IS NULL
AND 	PVENDA.DTACANCELAMENTO IS NULL
AND 	PVENDA.TIPPEDIDO NOT IN ('C', 'L')
AND 	PVENDA.DTAGERACAOCARGA IS NULL
AND		((PVENDA.TIPPEDIDO != 'B' AND PVENDA.SITUACAOPED IN ('L')) OR (PVENDA.TIPPEDIDO = 'B' AND PVENDA.SITUACAOPED = 'F'))
AND		PVENDAITEM.QTDATENDIDA 	> 	0
AND 	((PVENDA.TIPPEDIDO = 'B' AND PVENDA.DTAGERACAONF IS NOT NULL) OR (PVENDA.TIPPEDIDO != 'B' AND PVENDA.DTAGERACAONF IS NULL))
AND 	(NVL(PVENDA.indremessaentregafutura, 'N') = 'N' OR  (NVL(PVENDA.indremessaentregafutura, 'N') = 'S' 
AND 	NOT EXISTS (SELECT 1
          		    FROM implantacao.mad_pedvendaitem y
   								WHERE y.nroempresa = PVENDA.nroempresa
           		   	AND y.nropedvenda = PVENDA.nropedvenda
                  AND y.qtdatendida != y.qtdpedida))) 
AND		implantacao.fVerificaPedidoPrevio(PVENDA.CODGERALOPER) = 'N'
GROUP BY PVENDA.NROPEDVENDA,
				 PVENDA.DTABASEFATURAMENTO
ORDER BY PVENDA.NROPEDVENDA ASC
