SELECT SEQPESSOA,NOMPESSOA,SUM(VLRPAGO) VLRPAGO
FROM (SELECT FI_TITREPRES.SEQPESSOA SEQPESSOA,
             (SELECT NOMERAZAO FROM implantacao.GE_PESSOA WHERE SEQPESSOA = FI_TITREPRES.SEQPESSOA) NOMPESSOA,
             MAX(FI_TITULO.VLRNOMINAL) VLRNOMINAL,
             MAX(FI_TITULO.VLRPAGO) - (SELECT NVL(SUM(FI_TITOPERACAO.VLROPERACAO), 0)
                                       FROM implantacao.FI_OPERACAO, implantacao.FI_TITOPERACAO
                                       WHERE FI_OPERACAO.TIPOVALOR = 'A'
                                       AND NVL(FI_TITOPERACAO.OPCANCELADA, ' ') != 'C'
                                       AND FI_OPERACAO.CODOPERACAO = FI_TITOPERACAO.CODOPERACAO
                                       AND FI_TITOPERACAO.SEQTITULO = FI_TITULO.SEQTITULO) VLRPAGO,
              COUNT(1) NROTITULOS,
              MAX(FI_TITULO.VLRNOMINAL) - MAX(FI_TITULO.VLRPAGO) VLRABERTO
      FROM implantacao.FI_TITULO,
           implantacao.FI_TITREPRES,
           implantacao.FIV_COMISSAO,
           implantacao.FI_EVENTO,
           implantacao.GE_PESSOA P,
           implantacao.GE_PESSOA R
      WHERE FI_TITREPRES.SEQTITULO = FI_TITULO.SEQTITULO
      AND FI_TITULO.SEQTITULO = FIV_COMISSAO.SEQTITULO
      AND FIV_COMISSAO.CODEVENTO = FI_EVENTO.CODEVENTO
      AND FI_TITREPRES.SEQPESSOA = FIV_COMISSAO.SEQVENDEDOR
      AND FI_TITULO.NROEMPRESAMAE = '1'
      AND FI_TITULO.SITUACAO != 'C'
      AND FI_TITULO.NROEMPRESA IN (SELECT GE_EMPRESA.NROEMPRESA FROM implantacao.GE_EMPRESA WHERE GE_EMPRESA.STATUS = 'A')
      AND R.SEQPESSOA = FIV_COMISSAO.SEQVENDEDOR
      AND P.SEQPESSOA = FI_TITULO.SEQPESSOA
      --AND FI_TITULO.DTAQUITACAO BETWEEN '01-dec-2022' And '31-dec-2022'
      AND EXISTS(SELECT 1
                 FROM implantacao.FI_TITOPERACAO, implantacao.FI_TITULOCOMISSAO
                 WHERE FI_TITOPERACAO.SEQTITOPERACAO = FI_TITULOCOMISSAO.SEQTITOPERACAO
                 AND FI_TITULOCOMISSAO.SEQCOMISSAO = FIV_COMISSAO.SEQCOMISSAO
                 AND FI_TITULOCOMISSAO.INDCOMISSAO = 'L'
                 AND NVL(FI_TITOPERACAO.OPCANCELADA, ' ') != 'C'
                 AND FI_TITOPERACAO.DTAOPERACAO BETWEEN '01-dec-2022' AND '31-dec-2022')
      AND FI_TITULO.NROEMPRESA IN (1, 2)
      GROUP BY FI_TITULO.SEQTITULO,FI_TITREPRES.SEQPESSOA,P.NOMERAZAO)
GROUP BY SEQPESSOA,NOMPESSOA
ORDER BY NOMPESSOA ASC
