-- Primeiro dia do ano
SELECT TRUNC(ADD_MONTHS(SYSDATE, 0),'YY') FROM DUAL
-- Primeiro dia do mês
SELECT TRUNC(ADD_MONTHS(SYSDATE, 0),'MM') FROM DUAL
-- Último dia do mês
SELECT TRUNC(LAST_DAY(ADD_MONTHS(SYSDATE, -12))) FROM DUAL
--
SELECT TRUNC(SYSDATE)-1 FROM DUAL	 

SELECT SYSDATE-1 FROM DUAL